[package]
name = "nspire-leaveptt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnspire = "0.2.3"
rusb = "0.6.0"
